# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1037, 561)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.main_grid = QtGui.QGridLayout(self.centralwidget)
        self.main_grid.setObjectName(_fromUtf8("main_grid"))
        self.main_tabs = QtGui.QTabWidget(self.centralwidget)
        self.main_tabs.setObjectName(_fromUtf8("main_tabs"))
        self.file_tab = QtGui.QWidget()
        self.file_tab.setObjectName(_fromUtf8("file_tab"))
        self.main_file_grid = QtGui.QGridLayout(self.file_tab)
        self.main_file_grid.setObjectName(_fromUtf8("main_file_grid"))
        self.file_show_grid = QtGui.QGridLayout()
        self.file_show_grid.setObjectName(_fromUtf8("file_show_grid"))
        self.label = QtGui.QLabel(self.file_tab)
        self.label.setObjectName(_fromUtf8("label"))
        self.file_show_grid.addWidget(self.label, 0, 0, 1, 1)
        self.scrollArea = QtGui.QScrollArea(self.file_tab)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scroll_grid = QtGui.QWidget()
        self.scroll_grid.setGeometry(QtCore.QRect(0, 0, 96, 96))
        self.scroll_grid.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scroll_grid.setObjectName(_fromUtf8("scroll_grid"))
        self.gridLayout_5 = QtGui.QGridLayout(self.scroll_grid)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.plainTextEdit = QtGui.QPlainTextEdit(self.scroll_grid)
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.gridLayout_5.addWidget(self.plainTextEdit, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scroll_grid)
        self.file_show_grid.addWidget(self.scrollArea, 1, 0, 1, 1)
        self.main_file_grid.addLayout(self.file_show_grid, 2, 1, 1, 2)
        self.variable_grid = QtGui.QGridLayout()
        self.variable_grid.setObjectName(_fromUtf8("variable_grid"))
        self.label_3 = QtGui.QLabel(self.file_tab)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.variable_grid.addWidget(self.label_3, 2, 0, 1, 1)
        self.parameter_name = QtGui.QLineEdit(self.file_tab)
        self.parameter_name.setObjectName(_fromUtf8("parameter_name"))
        self.variable_grid.addWidget(self.parameter_name, 3, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.label_2 = QtGui.QLabel(self.file_tab)
        self.label_2.setMaximumSize(QtCore.QSize(331, 16777215))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.variable_grid.addWidget(self.label_2, 0, 0, 1, 1)
        self.variable_list = QtGui.QTableWidget(self.file_tab)
        self.variable_list.setColumnCount(2)
        self.variable_list.setObjectName(_fromUtf8("variable_list"))
        self.variable_list.setRowCount(0)
        self.variable_grid.addWidget(self.variable_list, 1, 0, 1, 3)
        self.parameter_add = QtGui.QPushButton(self.file_tab)
        self.parameter_add.setObjectName(_fromUtf8("parameter_add"))
        self.variable_grid.addWidget(self.parameter_add, 3, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.file_tab)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.variable_grid.addWidget(self.label_5, 2, 1, 1, 1)
        self.parameter_column = QtGui.QSpinBox(self.file_tab)
        self.parameter_column.setMinimum(1)
        self.parameter_column.setMaximum(10)
        self.parameter_column.setObjectName(_fromUtf8("parameter_column"))
        self.variable_grid.addWidget(self.parameter_column, 3, 1, 1, 1)
        self.main_file_grid.addLayout(self.variable_grid, 2, 0, 1, 1)
        self.file_choosing_grid = QtGui.QHBoxLayout()
        self.file_choosing_grid.setObjectName(_fromUtf8("file_choosing_grid"))
        self.combo_file = QtGui.QComboBox(self.file_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_file.sizePolicy().hasHeightForWidth())
        self.combo_file.setSizePolicy(sizePolicy)
        self.combo_file.setObjectName(_fromUtf8("combo_file"))
        self.file_choosing_grid.addWidget(self.combo_file)
        self.add_button = QtGui.QPushButton(self.file_tab)
        self.add_button.setObjectName(_fromUtf8("add_button"))
        self.file_choosing_grid.addWidget(self.add_button)
        self.remove_button = QtGui.QPushButton(self.file_tab)
        self.remove_button.setObjectName(_fromUtf8("remove_button"))
        self.file_choosing_grid.addWidget(self.remove_button)
        self.main_file_grid.addLayout(self.file_choosing_grid, 1, 0, 1, 3)
        self.label_4 = QtGui.QLabel(self.file_tab)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.main_file_grid.addWidget(self.label_4, 0, 0, 1, 1)
        self.main_tabs.addTab(self.file_tab, _fromUtf8(""))
        self.dataset_tab = QtGui.QWidget()
        self.dataset_tab.setObjectName(_fromUtf8("dataset_tab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.dataset_tab)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_8 = QtGui.QLabel(self.dataset_tab)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_6.addWidget(self.label_8, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_7 = QtGui.QLabel(self.dataset_tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_6.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.dataset_tab)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_6.addWidget(self.label_9, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_12 = QtGui.QLabel(self.dataset_tab)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_6.addWidget(self.label_12, 5, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_10 = QtGui.QLabel(self.dataset_tab)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_6.addWidget(self.label_10, 3, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_11 = QtGui.QLabel(self.dataset_tab)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_6.addWidget(self.label_11, 4, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.data_save = QtGui.QPushButton(self.dataset_tab)
        self.data_save.setObjectName(_fromUtf8("data_save"))
        self.gridLayout_6.addWidget(self.data_save, 6, 0, 1, 1)
        self.plot_button = QtGui.QPushButton(self.dataset_tab)
        self.plot_button.setObjectName(_fromUtf8("plot_button"))
        self.gridLayout_6.addWidget(self.plot_button, 6, 1, 1, 1)
        self.line_3 = QtGui.QFrame(self.dataset_tab)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout_6.addWidget(self.line_3, 0, 3, 7, 1)
        self.reset_plot_preview = QtGui.QPushButton(self.dataset_tab)
        self.reset_plot_preview.setObjectName(_fromUtf8("reset_plot_preview"))
        self.gridLayout_6.addWidget(self.reset_plot_preview, 6, 2, 1, 1)
        self.sy_data = QtGui.QLineEdit(self.dataset_tab)
        self.sy_data.setObjectName(_fromUtf8("sy_data"))
        self.gridLayout_6.addWidget(self.sy_data, 5, 1, 1, 2)
        self.sx_data = QtGui.QLineEdit(self.dataset_tab)
        self.sx_data.setObjectName(_fromUtf8("sx_data"))
        self.gridLayout_6.addWidget(self.sx_data, 4, 1, 1, 2)
        self.y_data = QtGui.QLineEdit(self.dataset_tab)
        self.y_data.setObjectName(_fromUtf8("y_data"))
        self.gridLayout_6.addWidget(self.y_data, 3, 1, 1, 2)
        self.x_data = QtGui.QLineEdit(self.dataset_tab)
        self.x_data.setAutoFillBackground(False)
        self.x_data.setObjectName(_fromUtf8("x_data"))
        self.gridLayout_6.addWidget(self.x_data, 2, 1, 1, 2)
        self.label_data = QtGui.QLineEdit(self.dataset_tab)
        self.label_data.setText(_fromUtf8(""))
        self.label_data.setObjectName(_fromUtf8("label_data"))
        self.gridLayout_6.addWidget(self.label_data, 1, 1, 1, 2)
        self.line = QtGui.QFrame(self.dataset_tab)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_6.addWidget(self.line, 0, 1, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout_6, 1, 0, 8, 1)
        self.matplotlib_grid = QtGui.QGridLayout()
        self.matplotlib_grid.setObjectName(_fromUtf8("matplotlib_grid"))
        self.label_13 = QtGui.QLabel(self.dataset_tab)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.matplotlib_grid.addWidget(self.label_13, 0, 0, 1, 1, QtCore.Qt.AlignBottom)
        self.line_2 = QtGui.QFrame(self.dataset_tab)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.matplotlib_grid.addWidget(self.line_2, 1, 0, 1, 1, QtCore.Qt.AlignTop)
        self.gridLayout_2.addLayout(self.matplotlib_grid, 1, 1, 8, 2)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.combo_set = QtGui.QComboBox(self.dataset_tab)
        self.combo_set.setObjectName(_fromUtf8("combo_set"))
        self.gridLayout.addWidget(self.combo_set, 1, 0, 1, 6, QtCore.Qt.AlignTop)
        self.remove_dataset = QtGui.QPushButton(self.dataset_tab)
        self.remove_dataset.setObjectName(_fromUtf8("remove_dataset"))
        self.gridLayout.addWidget(self.remove_dataset, 1, 7, 1, 1)
        self.add_dataset = QtGui.QPushButton(self.dataset_tab)
        self.add_dataset.setObjectName(_fromUtf8("add_dataset"))
        self.gridLayout.addWidget(self.add_dataset, 1, 6, 1, 1)
        self.label_6 = QtGui.QLabel(self.dataset_tab)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 3)
        self.main_tabs.addTab(self.dataset_tab, _fromUtf8(""))
        self.fit_tab = QtGui.QWidget()
        self.fit_tab.setObjectName(_fromUtf8("fit_tab"))
        self.gridLayout_4 = QtGui.QGridLayout(self.fit_tab)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.fit_plot_grid = QtGui.QGridLayout()
        self.fit_plot_grid.setObjectName(_fromUtf8("fit_plot_grid"))
        self.label_14 = QtGui.QLabel(self.fit_tab)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.fit_plot_grid.addWidget(self.label_14, 0, 0, 1, 1, QtCore.Qt.AlignBottom)
        self.line_8 = QtGui.QFrame(self.fit_tab)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.fit_plot_grid.addWidget(self.line_8, 1, 0, 1, 1, QtCore.Qt.AlignTop)
        self.gridLayout_4.addLayout(self.fit_plot_grid, 1, 2, 8, 2)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.combo_fit = QtGui.QComboBox(self.fit_tab)
        self.combo_fit.setObjectName(_fromUtf8("combo_fit"))
        self.gridLayout_3.addWidget(self.combo_fit, 1, 0, 1, 6)
        self.add_fit = QtGui.QPushButton(self.fit_tab)
        self.add_fit.setObjectName(_fromUtf8("add_fit"))
        self.gridLayout_3.addWidget(self.add_fit, 1, 6, 1, 1)
        self.delete_fit = QtGui.QPushButton(self.fit_tab)
        self.delete_fit.setObjectName(_fromUtf8("delete_fit"))
        self.gridLayout_3.addWidget(self.delete_fit, 1, 7, 1, 1)
        self.label_25 = QtGui.QLabel(self.fit_tab)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_3.addWidget(self.label_25, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 4)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.min_range = QtGui.QLineEdit(self.fit_tab)
        self.min_range.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.min_range.setObjectName(_fromUtf8("min_range"))
        self.gridLayout_7.addWidget(self.min_range, 7, 1, 1, 2, QtCore.Qt.AlignHCenter)
        self.param_uncert = QtGui.QLineEdit(self.fit_tab)
        self.param_uncert.setObjectName(_fromUtf8("param_uncert"))
        self.gridLayout_7.addWidget(self.param_uncert, 11, 1, 1, 2)
        self.label_21 = QtGui.QLabel(self.fit_tab)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_7.addWidget(self.label_21, 10, 0, 1, 1)
        self.check_uncertainties = QtGui.QCheckBox(self.fit_tab)
        self.check_uncertainties.setText(_fromUtf8(""))
        self.check_uncertainties.setObjectName(_fromUtf8("check_uncertainties"))
        self.gridLayout_7.addWidget(self.check_uncertainties, 5, 1, 1, 1)
        self.param_val = QtGui.QLineEdit(self.fit_tab)
        self.param_val.setObjectName(_fromUtf8("param_val"))
        self.gridLayout_7.addWidget(self.param_val, 10, 1, 1, 2)
        self.label_22 = QtGui.QLabel(self.fit_tab)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_7.addWidget(self.label_22, 11, 0, 1, 1)
        self.line_4 = QtGui.QFrame(self.fit_tab)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout_7.addWidget(self.line_4, 6, 0, 1, 1)
        self.label_15 = QtGui.QLabel(self.fit_tab)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_7.addWidget(self.label_15, 3, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.fit_tab)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_7.addWidget(self.label_16, 4, 0, 1, 1)
        self.fit_label = QtGui.QLineEdit(self.fit_tab)
        self.fit_label.setObjectName(_fromUtf8("fit_label"))
        self.gridLayout_7.addWidget(self.fit_label, 3, 1, 1, 2)
        self.label_17 = QtGui.QLabel(self.fit_tab)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_7.addWidget(self.label_17, 5, 0, 1, 1)
        self.fit_function = QtGui.QComboBox(self.fit_tab)
        self.fit_function.setObjectName(_fromUtf8("fit_function"))
        self.gridLayout_7.addWidget(self.fit_function, 4, 1, 1, 2)
        self.manage_functions = QtGui.QToolButton(self.fit_tab)
        self.manage_functions.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.manage_functions.setArrowType(QtCore.Qt.NoArrow)
        self.manage_functions.setObjectName(_fromUtf8("manage_functions"))
        self.gridLayout_7.addWidget(self.manage_functions, 4, 3, 1, 1)
        self.label_23 = QtGui.QLabel(self.fit_tab)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_7.addWidget(self.label_23, 9, 1, 1, 2)
        self.start_fit = QtGui.QPushButton(self.fit_tab)
        self.start_fit.setObjectName(_fromUtf8("start_fit"))
        self.gridLayout_7.addWidget(self.start_fit, 11, 3, 1, 1)
        self.line_5 = QtGui.QFrame(self.fit_tab)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.gridLayout_7.addWidget(self.line_5, 9, 0, 1, 1)
        self.line_7 = QtGui.QFrame(self.fit_tab)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.gridLayout_7.addWidget(self.line_7, 1, 1, 1, 3)
        self.save_fit = QtGui.QPushButton(self.fit_tab)
        self.save_fit.setObjectName(_fromUtf8("save_fit"))
        self.gridLayout_7.addWidget(self.save_fit, 10, 3, 1, 1)
        self.label_24 = QtGui.QLabel(self.fit_tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_7.addWidget(self.label_24, 1, 0, 1, 1)
        self.line_9 = QtGui.QFrame(self.fit_tab)
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.gridLayout_7.addWidget(self.line_9, 6, 3, 1, 1)
        self.max_range = QtGui.QLineEdit(self.fit_tab)
        self.max_range.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.max_range.setObjectName(_fromUtf8("max_range"))
        self.gridLayout_7.addWidget(self.max_range, 8, 1, 1, 2)
        self.label_20 = QtGui.QLabel(self.fit_tab)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_7.addWidget(self.label_20, 8, 0, 1, 1)
        self.label_19 = QtGui.QLabel(self.fit_tab)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_7.addWidget(self.label_19, 7, 0, 1, 1)
        self.label_18 = QtGui.QLabel(self.fit_tab)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_7.addWidget(self.label_18, 6, 1, 1, 2)
        self.graphic_range = QtGui.QPushButton(self.fit_tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.graphic_range.setFont(font)
        self.graphic_range.setObjectName(_fromUtf8("graphic_range"))
        self.gridLayout_7.addWidget(self.graphic_range, 7, 3, 2, 1)
        self.gridLayout_4.addLayout(self.gridLayout_7, 1, 0, 8, 1)
        self.line_6 = QtGui.QFrame(self.fit_tab)
        self.line_6.setFrameShape(QtGui.QFrame.VLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.gridLayout_4.addWidget(self.line_6, 1, 1, 8, 1)
        self.main_tabs.addTab(self.fit_tab, _fromUtf8(""))
        self.main_grid.addWidget(self.main_tabs, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1037, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionOpen)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.main_tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "File Content", None))
        self.label_3.setText(_translate("MainWindow", "Variable", None))
        self.label_2.setText(_translate("MainWindow", "Set Variables", None))
        self.parameter_add.setText(_translate("MainWindow", "Add/Edit", None))
        self.label_5.setText(_translate("MainWindow", "Row(column)", None))
        self.add_button.setText(_translate("MainWindow", "Add", None))
        self.remove_button.setText(_translate("MainWindow", "Delete", None))
        self.label_4.setText(_translate("MainWindow", "Select File", None))
        self.main_tabs.setTabText(self.main_tabs.indexOf(self.file_tab), _translate("MainWindow", "Files", None))
        self.label_8.setText(_translate("MainWindow", "Dataset Label", None))
        self.label_7.setText(_translate("MainWindow", "Dataset Properties", None))
        self.label_9.setText(_translate("MainWindow", "X axis", None))
        self.label_12.setText(_translate("MainWindow", "Y Uncertainties", None))
        self.label_10.setText(_translate("MainWindow", "Y axis", None))
        self.label_11.setText(_translate("MainWindow", "X Uncertainties", None))
        self.data_save.setText(_translate("MainWindow", "Save/Edit", None))
        self.plot_button.setText(_translate("MainWindow", "Preview", None))
        self.reset_plot_preview.setText(_translate("MainWindow", "Clear Plot", None))
        self.label_13.setText(_translate("MainWindow", "Simple Plot. Its purpouse is only to check the data of the dataset", None))
        self.remove_dataset.setText(_translate("MainWindow", "Remove", None))
        self.add_dataset.setText(_translate("MainWindow", "Add New", None))
        self.label_6.setText(_translate("MainWindow", "Select Data set or Create a New One", None))
        self.main_tabs.setTabText(self.main_tabs.indexOf(self.dataset_tab), _translate("MainWindow", "Data sets", None))
        self.label_14.setText(_translate("MainWindow", "Fit Result", None))
        self.add_fit.setText(_translate("MainWindow", "Add", None))
        self.delete_fit.setText(_translate("MainWindow", "Delete", None))
        self.label_25.setText(_translate("MainWindow", "Select a fit or create a new one", None))
        self.label_21.setText(_translate("MainWindow", "Parameters", None))
        self.label_22.setText(_translate("MainWindow", "Uncertainties", None))
        self.label_15.setText(_translate("MainWindow", "Label", None))
        self.label_16.setText(_translate("MainWindow", "Fitting Function", None))
        self.label_17.setText(_translate("MainWindow", "Uncertainties", None))
        self.manage_functions.setText(_translate("MainWindow", "...", None))
        self.label_23.setText(_translate("MainWindow", "Result/initial Value", None))
        self.start_fit.setText(_translate("MainWindow", "Fit", None))
        self.save_fit.setText(_translate("MainWindow", "Save", None))
        self.label_24.setText(_translate("MainWindow", "Fit Properties", None))
        self.label_20.setText(_translate("MainWindow", "Max", None))
        self.label_19.setText(_translate("MainWindow", "Min", None))
        self.label_18.setText(_translate("MainWindow", "Data Range", None))
        self.graphic_range.setText(_translate("MainWindow", "Set graphically", None))
        self.main_tabs.setTabText(self.main_tabs.indexOf(self.fit_tab), _translate("MainWindow", "Fit Data", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionOpen.setText(_translate("MainWindow", "Open", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

