# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1045, 701)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.main_grid = QtGui.QGridLayout(self.centralwidget)
        self.main_grid.setObjectName(_fromUtf8("main_grid"))
        self.main_tabs = QtGui.QTabWidget(self.centralwidget)
        self.main_tabs.setObjectName(_fromUtf8("main_tabs"))
        self.file_tab = QtGui.QWidget()
        self.file_tab.setObjectName(_fromUtf8("file_tab"))
        self.main_file_grid = QtGui.QGridLayout(self.file_tab)
        self.main_file_grid.setObjectName(_fromUtf8("main_file_grid"))
        self.file_show_grid = QtGui.QGridLayout()
        self.file_show_grid.setObjectName(_fromUtf8("file_show_grid"))
        self.label = QtGui.QLabel(self.file_tab)
        self.label.setObjectName(_fromUtf8("label"))
        self.file_show_grid.addWidget(self.label, 0, 0, 1, 1)
        self.scrollArea = QtGui.QScrollArea(self.file_tab)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scroll_grid = QtGui.QWidget()
        self.scroll_grid.setGeometry(QtCore.QRect(0, 0, 661, 500))
        self.scroll_grid.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scroll_grid.setObjectName(_fromUtf8("scroll_grid"))
        self.gridLayout_5 = QtGui.QGridLayout(self.scroll_grid)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.plainTextEdit = QtGui.QPlainTextEdit(self.scroll_grid)
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.gridLayout_5.addWidget(self.plainTextEdit, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scroll_grid)
        self.file_show_grid.addWidget(self.scrollArea, 1, 0, 1, 1)
        self.main_file_grid.addLayout(self.file_show_grid, 2, 1, 1, 2)
        self.variable_grid = QtGui.QGridLayout()
        self.variable_grid.setObjectName(_fromUtf8("variable_grid"))
        self.label_3 = QtGui.QLabel(self.file_tab)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.variable_grid.addWidget(self.label_3, 2, 0, 1, 1)
        self.parameter_name = QtGui.QLineEdit(self.file_tab)
        self.parameter_name.setObjectName(_fromUtf8("parameter_name"))
        self.variable_grid.addWidget(self.parameter_name, 3, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.label_2 = QtGui.QLabel(self.file_tab)
        self.label_2.setMaximumSize(QtCore.QSize(331, 16777215))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.variable_grid.addWidget(self.label_2, 0, 0, 1, 1)
        self.variable_list = QtGui.QTableWidget(self.file_tab)
        self.variable_list.setColumnCount(2)
        self.variable_list.setObjectName(_fromUtf8("variable_list"))
        self.variable_list.setRowCount(0)
        self.variable_grid.addWidget(self.variable_list, 1, 0, 1, 3)
        self.parameter_add = QtGui.QPushButton(self.file_tab)
        self.parameter_add.setObjectName(_fromUtf8("parameter_add"))
        self.variable_grid.addWidget(self.parameter_add, 3, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.file_tab)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.variable_grid.addWidget(self.label_5, 2, 1, 1, 1)
        self.parameter_column = QtGui.QSpinBox(self.file_tab)
        self.parameter_column.setMinimum(1)
        self.parameter_column.setMaximum(10)
        self.parameter_column.setObjectName(_fromUtf8("parameter_column"))
        self.variable_grid.addWidget(self.parameter_column, 3, 1, 1, 1)
        self.main_file_grid.addLayout(self.variable_grid, 2, 0, 1, 1)
        self.file_choosing_grid = QtGui.QHBoxLayout()
        self.file_choosing_grid.setObjectName(_fromUtf8("file_choosing_grid"))
        self.combo_file = QtGui.QComboBox(self.file_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_file.sizePolicy().hasHeightForWidth())
        self.combo_file.setSizePolicy(sizePolicy)
        self.combo_file.setObjectName(_fromUtf8("combo_file"))
        self.file_choosing_grid.addWidget(self.combo_file)
        self.add_button = QtGui.QPushButton(self.file_tab)
        self.add_button.setObjectName(_fromUtf8("add_button"))
        self.file_choosing_grid.addWidget(self.add_button)
        self.remove_button = QtGui.QPushButton(self.file_tab)
        self.remove_button.setObjectName(_fromUtf8("remove_button"))
        self.file_choosing_grid.addWidget(self.remove_button)
        self.main_file_grid.addLayout(self.file_choosing_grid, 1, 0, 1, 3)
        self.label_4 = QtGui.QLabel(self.file_tab)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.main_file_grid.addWidget(self.label_4, 0, 0, 1, 1)
        self.main_tabs.addTab(self.file_tab, _fromUtf8(""))
        self.dataset_tab = QtGui.QWidget()
        self.dataset_tab.setObjectName(_fromUtf8("dataset_tab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.dataset_tab)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_8 = QtGui.QLabel(self.dataset_tab)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_6.addWidget(self.label_8, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_7 = QtGui.QLabel(self.dataset_tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_6.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.dataset_tab)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_6.addWidget(self.label_9, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.y_data = QtGui.QLineEdit(self.dataset_tab)
        self.y_data.setObjectName(_fromUtf8("y_data"))
        self.gridLayout_6.addWidget(self.y_data, 3, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.x_data = QtGui.QLineEdit(self.dataset_tab)
        self.x_data.setAutoFillBackground(False)
        self.x_data.setObjectName(_fromUtf8("x_data"))
        self.gridLayout_6.addWidget(self.x_data, 2, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.sx_data = QtGui.QLineEdit(self.dataset_tab)
        self.sx_data.setObjectName(_fromUtf8("sx_data"))
        self.gridLayout_6.addWidget(self.sx_data, 4, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_12 = QtGui.QLabel(self.dataset_tab)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_6.addWidget(self.label_12, 5, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.sy_data = QtGui.QLineEdit(self.dataset_tab)
        self.sy_data.setObjectName(_fromUtf8("sy_data"))
        self.gridLayout_6.addWidget(self.sy_data, 5, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_10 = QtGui.QLabel(self.dataset_tab)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_6.addWidget(self.label_10, 3, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.line = QtGui.QFrame(self.dataset_tab)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_6.addWidget(self.line, 0, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.dataset_tab)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_6.addWidget(self.label_11, 4, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.plot_button = QtGui.QPushButton(self.dataset_tab)
        self.plot_button.setObjectName(_fromUtf8("plot_button"))
        self.gridLayout_6.addWidget(self.plot_button, 6, 1, 1, 1)
        self.label_data = QtGui.QLineEdit(self.dataset_tab)
        self.label_data.setText(_fromUtf8(""))
        self.label_data.setObjectName(_fromUtf8("label_data"))
        self.gridLayout_6.addWidget(self.label_data, 1, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.data_save = QtGui.QPushButton(self.dataset_tab)
        self.data_save.setObjectName(_fromUtf8("data_save"))
        self.gridLayout_6.addWidget(self.data_save, 6, 0, 1, 1)
        self.line_3 = QtGui.QFrame(self.dataset_tab)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout_6.addWidget(self.line_3, 0, 2, 7, 1)
        self.gridLayout_2.addLayout(self.gridLayout_6, 1, 0, 8, 1)
        self.matplotlib_grid = QtGui.QGridLayout()
        self.matplotlib_grid.setObjectName(_fromUtf8("matplotlib_grid"))
        self.label_13 = QtGui.QLabel(self.dataset_tab)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.matplotlib_grid.addWidget(self.label_13, 0, 0, 1, 1, QtCore.Qt.AlignBottom)
        self.line_2 = QtGui.QFrame(self.dataset_tab)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.matplotlib_grid.addWidget(self.line_2, 1, 0, 1, 1, QtCore.Qt.AlignTop)
        self.gridLayout_2.addLayout(self.matplotlib_grid, 1, 1, 8, 2)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.combo_set = QtGui.QComboBox(self.dataset_tab)
        self.combo_set.setObjectName(_fromUtf8("combo_set"))
        self.gridLayout.addWidget(self.combo_set, 1, 0, 1, 6, QtCore.Qt.AlignTop)
        self.remove_dataset = QtGui.QPushButton(self.dataset_tab)
        self.remove_dataset.setObjectName(_fromUtf8("remove_dataset"))
        self.gridLayout.addWidget(self.remove_dataset, 1, 7, 1, 1)
        self.add_dataset = QtGui.QPushButton(self.dataset_tab)
        self.add_dataset.setObjectName(_fromUtf8("add_dataset"))
        self.gridLayout.addWidget(self.add_dataset, 1, 6, 1, 1)
        self.label_6 = QtGui.QLabel(self.dataset_tab)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 3)
        self.main_tabs.addTab(self.dataset_tab, _fromUtf8(""))
        self.main_grid.addWidget(self.main_tabs, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1045, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionOpen)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.main_tabs.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "File Content", None))
        self.label_3.setText(_translate("MainWindow", "Variable", None))
        self.label_2.setText(_translate("MainWindow", "Set Variables", None))
        self.parameter_add.setText(_translate("MainWindow", "Add/Edit", None))
        self.label_5.setText(_translate("MainWindow", "Row(column)", None))
        self.add_button.setText(_translate("MainWindow", "Add", None))
        self.remove_button.setText(_translate("MainWindow", "Delete", None))
        self.label_4.setText(_translate("MainWindow", "Select File", None))
        self.main_tabs.setTabText(self.main_tabs.indexOf(self.file_tab), _translate("MainWindow", "Files", None))
        self.label_8.setText(_translate("MainWindow", "Dataset Label", None))
        self.label_7.setText(_translate("MainWindow", "Dataset Properties", None))
        self.label_9.setText(_translate("MainWindow", "X axis", None))
        self.label_12.setText(_translate("MainWindow", "Y Uncertainties", None))
        self.label_10.setText(_translate("MainWindow", "Y axis", None))
        self.label_11.setText(_translate("MainWindow", "X Uncertainties", None))
        self.plot_button.setText(_translate("MainWindow", "Preview", None))
        self.data_save.setText(_translate("MainWindow", "Save/Edit", None))
        self.label_13.setText(_translate("MainWindow", "Simple Plot. Its purpouse is only to check the data of the dataset", None))
        self.remove_dataset.setText(_translate("MainWindow", "Remove", None))
        self.add_dataset.setText(_translate("MainWindow", "Add New", None))
        self.label_6.setText(_translate("MainWindow", "Select Data set or Create a New One", None))
        self.main_tabs.setTabText(self.main_tabs.indexOf(self.dataset_tab), _translate("MainWindow", "Data sets", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionOpen.setText(_translate("MainWindow", "Open", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

